### ISSUE TITLE
mklink not worked

### ISSUE THREAD

**Issue by AnggonoUtomo** [Roffild/RoffildLibrary#4]
Hi Roffild,

this great project, but i cant install it using mklink on my windows 7 pc. any solution with that?
![Untitled](https://user-images.githubusercontent.com/1715812/64200317-75f6f780-ceb6-11e9-80e8-325231d7aeaf.png)

**Comment by Roffild** [comment]
May be
```bat
mklink /j "%APPDATA%\MetaQuotes" "D:\MQLProjects"
```

**Comment by AnggonoUtomo** [comment]
ok, that's work, thanks for advice... :)

**Comment by AnggonoUtomo** [comment]
hi Roffild, 

Again, i found this :

`D:\MQLProjects\RoffildLibrary\Indicators\Roffild\ToIndicator.mq5 - FAIL
D:\MQLProjects\RoffildLibrary\Indicators\Roffild\ToIndicator.mqh - FAIL
D:\MQLProjects\RoffildLibrary\Indicators\Roffild\ToIndicator_window.mq5 - FAIL
D:\MQLProjects\RoffildLibrary\Scripts\Roffild\UnitTests\ArrayList_UnitTest.mq5 - FAIL
D:\MQLProjects\RoffildLibrary\Scripts\Roffild\UnitTests\Log4MQL_UnitTest.mq5 - FAIL
D:\MQLProjects\RoffildLibrary\Scripts\Roffild\UnitTests\MLPDataFile_UnitTest.mq5 - FAIL
D:\MQLProjects\RoffildLibrary\Scripts\Roffild\UnitTests\Serialization_UnitTest.mq5 - FAIL
Obtaining file:///D:/MQLProjects/RoffildLibrary/Include/Roffild/RoffildPython
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\XRAY~1\\AppData\\Local\\Temp\\pip-req-tracker-4uo2lc8f\\834659a94ab542192abbdbd4d2eb990ccec1b423e11610d78a0a95e6'`

After Execute 'buildall_and_tests.py'

**Comment by Roffild** [comment]
The path is wrong.

> (Important)
> Run the create_links.bat from the MQL5\MyProjects\RoffildLibrary folder after cloning the project.

That is, create_links.bat should be in D:\MQLProjects\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\MQL5\MyProjects\RoffildLibrary or in D:\MQLProjects\MQL5\MyProjects\RoffildLibrary if there is a link ``` mklink /j D:\MQLProjects\MQL5 D:\MQLProjects\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\MQL5 ```

Where: 

D0E8209F77C8CF37AD8BF550E51FF075 = md5(C:\Program Files\MetaTrader 5)

MyProjects = any folder name
