### ISSUE TITLE
Updating aws_ubuntu_user_data.sh

### ISSUE THREAD

**Issue by gkourogiorgas** [Roffild/RoffildLibrary#5]
Hi. Very nice work with AWS and MT5 agents. I believe the .sh file needs to be updates. Wine is not installed like in the script. They have changed something with the key and how it is verified. It is a nuissance even for manual installations...
Is it possible to. update it?
Also, is aws cheaper for the same result(equivalent of passes)?

**Comment by Roffild** [comment]
Thank you for message.

[FAudio for Debian 10 and Ubuntu 18.04](https://forum.winehq.org/viewtopic.php?t=32192)

I updated the script to run the agents.
[aws_ubuntu_user_data.sh](https://github.com/Roffild/RoffildLibrary/blob/master/Include/Roffild/RoffildJava/AmazonUtils/src/main/resources/aws_ubuntu_user_data.sh)
